// doctor appointments
export const appointments = [
  {
    time: "08:00 AM",
    duration: 30,
    patient: null,
    type: "Available",
  },
  {
    time: "08:30 AM",
    duration: 30,
    patient: null,
    type: "Available",
  },
  {
    time: "09:00 AM",
    duration: 60,
    patient: "Rajesh Sharma",
    type: "Follow-up Consultation",
    room: "Room 204",
    dept: "Cardiology",
    status: "completed",
    initials: "RS",
  },
  {
    time: "10:00 AM",
    duration: 30,
    patient: null,
    type: "Available",
  },
  {
    time: "10:30 AM",
    duration: 60,
    patient: "Priya Verma",
    type: "Cardiology Consultation",
    room: "Room 204",
    dept: "Cardiology",
    status: "in-progress",
    initials: "PV",
  },
  {
    time: "11:00 AM",
    duration: 60,
    patient: "Amit Kumar",
    type: "ECG Review",
    room: "Room 204",
    dept: "Cardiology",
    status: "upcoming",
    initials: "AK",
  },
  {
    time: "11:30 AM",
    duration: 30,
    patient: null,
    type: "Available",
  },
  {
    time: "12:00 PM",
    duration: 60,
    patient: "Lunch Break",
    type: "break",
    status: "break",
  },
  {
    time: "01:00 PM",
    duration: 30,
    patient: null,
    type: "Available",
  },
  {
    time: "02:00 PM",
    duration: 60,
    patient: "Neha Gupta",
    type: "New Patient Consultation",
    room: "Room 204",
    dept: "Cardiology",
    status: "upcoming",
    initials: "NG",
  },
  {
    time: "03:00 PM",
    duration: 30,
    patient: null,
    type: "Available",
  },
  {
    time: "03:30 PM",
    duration: 60,
    patient: "Vikram Singh",
    type: "Follow-up",
    room: "Room 204",
    dept: "Cardiology",
    status: "upcoming",
    initials: "VS",
  },
  {
    time: "04:30 PM",
    duration: 60,
    patient: null,
    type: "Available",
  },
  {
    time: "05:30 PM",
    duration: 30,
    patient: null,
    type: "Available",
  },
];
