import type {
  Patient,
  Doctor,
  Appointment,
  MedicalRecord,
  Prescription,
  LabReport,
  Payment,
  Notification,
  HealthTip,
  Vital,
} from "./types";

export const patient: Patient = {
  slug: "akriti-sharma",
  name: "Akriti Sharma",
  patientId: "PT-2024-0587",
  email: "akriti.sharma@email.com",
  phone: "+1 (555) 123-4567",
  dob: "Apr 15, 1990",
  age: 36,
  gender: "Female",
  bloodType: "O+",
  address: "221B Maple Street, Springfield, IL 62704",
  emergencyContact: {
    name: "Akaay sharma",
    relation: "Spouse",
    phone: "+1 (555) 987-6543",
  },
  insurance: {
    provider: "BlueHorizon Health Insurance",
    policyNumber: "BH-88213-SJ",
    group: "GRP-4471",
  },
  allergies: ["Penicillin", "Pollen"],
  conditions: ["Mild Hypertension"],
};

export const doctors: Doctor[] = [
  {
    id: "doc-1",
    name: "Dr.Anwar Hussain",
    specialty: "General Physician",
    hospital: "MediCare Central",
    rating: 4.9,
    years: 14,
    availability: "Mon–Fri",
    initials: "MC",
    color: "brand",
  },
  {
    id: "doc-2",
    name: "Dr. Shreya Satti",
    specialty: "Cardiologist",
    hospital: "MediCare Heart Institute",
    rating: 4.8,
    years: 11,
    availability: "Tue, Thu",
    initials: "EC",
    color: "accent",
  },
  {
    id: "doc-3",
    name: "Dr. Aisha Patel",
    specialty: "Dermatologist",
    hospital: "MediCare Central",
    rating: 4.7,
    years: 8,
    availability: "Mon, Wed, Fri",
    initials: "AP",
    color: "ink",
  },
  {
    id: "doc-4",
    name: "Dr. Sonja ",
    specialty: "Orthopedic Specialist",
    hospital: "MediCare Bone & Joint",
    rating: 4.9,
    years: 16,
    availability: "Wed–Sat",
    initials: "RK",
    color: "brand",
  },
];

export const upcomingAppointment: Appointment = {
  id: "apt-1042",
  doctor: doctors[0],
  date: "Aug 25, 2026",
  day: "Tuesday",
  time: "10:30 AM",
  type: "In-person",
  location: "MediCare Central · Room 204",
  status: "Confirmed",
  reason: "Routine Checkup",
};

export const appointments: Appointment[] = [
  upcomingAppointment,
  {
    id: "apt-1041",
    doctor: doctors[1],
    date: "Sep 2, 2026",
    day: "Wednesday",
    time: "2:00 PM",
    type: "Video Call",
    location: "Online Consultation",
    status: "Confirmed",
    reason: "Cardiology Follow-up",
  },
  {
    id: "apt-1038",
    doctor: doctors[3],
    date: "Jul 15, 2026",
    day: "Wednesday",
    time: "9:00 AM",
    type: "In-person",
    location: "MediCare Bone & Joint · Room 3",
    status: "Completed",
    reason: "Right Knee X-Ray Review",
  },
  {
    id: "apt-1030",
    doctor: doctors[2],
    date: "Jun 28, 2026",
    day: "Sunday",
    time: "11:15 AM",
    type: "In-person",
    location: "MediCare Central · Room 118",
    status: "Completed",
    reason: "Skin Allergy Consultation",
  },
  {
    id: "apt-1022",
    doctor: doctors[0],
    date: "Jun 3, 2026",
    day: "Wednesday",
    time: "4:30 PM",
    type: "Video Call",
    location: "Online Consultation",
    status: "Cancelled",
    reason: "Prescription Review",
  },
];

export const medicalRecords: MedicalRecord[] = [
  {
    id: "rec-1",
    title: "Annual Physical Examination",
    category: "Consultation",
    doctor: "Dr.Anwar Hussain",
    date: "Aug 10, 2026",
    summary: "General checkup — vitals stable, no concerns noted.",
    fileSize: "1.2 MB",
  },
  {
    id: "rec-2",
    title: "Cardiology Consultation Notes",
    category: "Consultation",
    doctor: "Dr.Shreya Satti",
    date: "Jul 28, 2026",
    summary: "Follow-up on mild hypertension, medication adjusted.",
    fileSize: "860 KB",
  },
  {
    id: "rec-3",
    title: "Right Knee X-Ray",
    category: "Imaging",
    doctor: "Dr.Sonja",
    date: "Jul 15, 2026",
    summary: "No fracture. Mild inflammation of the patellar tendon.",
    fileSize: "3.4 MB",
  },
  {
    id: "rec-4",
    title: "Seasonal Allergy Panel",
    category: "Lab",
    doctor: "Dr. Aisha Patel",
    date: "Jun 28, 2026",
    summary: "Confirmed pollen sensitivity, penicillin allergy noted.",
    fileSize: "540 KB",
  },
  {
    id: "rec-5",
    title: "Influenza Vaccination Record",
    category: "Vaccination",
    doctor: "Dr. Anwar Hussain",
    date: "Apr 2, 2026",
    summary: "Seasonal flu shot administered, no adverse reaction.",
    fileSize: "210 KB",
  },
];

export const prescriptions: Prescription[] = [
  {
    id: "rx-1",
    medication: "Atorvastatin 10mg",
    dosage: "1 tablet",
    frequency: "Once daily · evening",
    doctor: "Dr. Shreya Satti",
    startDate: "Jul 28, 2026",
    duration: "90 days",
    refillsLeft: 2,
    status: "Active",
  },
  {
    id: "rx-2",
    medication: "Lisinopril 5mg",
    dosage: "1 tablet",
    frequency: "Once daily · morning",
    doctor: "Dr. Anwar Hussain",
    startDate: "Aug 10, 2026",
    duration: "60 days",
    refillsLeft: 3,
    status: "Active",
  },
  {
    id: "rx-3",
    medication: "Cetirizine 10mg",
    dosage: "1 tablet",
    frequency: "As needed",
    doctor: "Dr. Aisha Patel",
    startDate: "Jun 28, 2026",
    duration: "30 days",
    refillsLeft: 1,
    status: "Active",
  },
  {
    id: "rx-4",
    medication: "Ibuprofen 400mg",
    dosage: "1 tablet",
    frequency: "Every 8 hours · as needed",
    doctor: "Dr. Sonja",
    startDate: "Jul 15, 2026",
    duration: "14 days",
    refillsLeft: 0,
    status: "Expired",
  },
];

export const labReports: LabReport[] = [
  {
    id: "lab-1",
    testName: "Complete Blood Count (CBC)",
    category: "Hematology",
    date: "Aug 5, 2026",
    doctor: "Dr. Anwar Hussain",
    status: "Ready",
    flagged: false,
  },
  {
    id: "lab-2",
    testName: "Lipid Profile",
    category: "Biochemistry",
    date: "Aug 5, 2026",
    doctor: "Dr. Shreya Satti",
    status: "Ready",
    flagged: true,
  },
  {
    id: "lab-3",
    testName: "Thyroid Function Test",
    category: "Endocrinology",
    date: "Jul 20, 2026",
    doctor: "Dr. Anwar Hussain",
    status: "Ready",
    flagged: false,
  },
  {
    id: "lab-4",
    testName: "Right Knee X-Ray",
    category: "Radiology",
    date: "Jul 15, 2026",
    doctor: "Dr. Sonja",
    status: "In Review",
    flagged: false,
  },
  {
    id: "lab-5",
    testName: "Allergy Panel",
    category: "Immunology",
    date: "Jun 28, 2026",
    doctor: "Dr. Aisha Patel",
    status: "Ready",
    flagged: false,
  },
];

export const payments: Payment[] = [
  {
    id: "pay-1",
    description: "General Consultation",
    category: "Consultation",
    date: "Aug 10, 2026",
    amount: 1500,
    status: "Paid",
    method: "Visa •••• 4821",
    invoiceNo: "INV-58231",
  },
  {
    id: "pay-2",
    description: "CBC & Lipid Profile Lab Panel",
    category: "Lab Tests",
    date: "Aug 5, 2026",
    amount: 8500,
    status: "Paid",
    method: "Insurance Claim",
    invoiceNo: "INV-58190",
  },
  {
    id: "pay-3",
    description: "Right Knee X-Ray",
    category: "Imaging",
    date: "Jul 15, 2026",
    amount: 2200,
    status: "Paid",
    method: "Visa •••• 4821",
    invoiceNo: "INV-57988",
  },
  {
    id: "pay-4",
    description: "Pharmacy — Prescription Refill",
    category: "Pharmacy",
    date: "Aug 18, 2026",
    amount: 4500,
    status: "Pending",
    method: "—",
    invoiceNo: "INV-58305",
  },
];

export const notifications: Notification[] = [
  {
    id: "notif-1",
    title: "Appointment reminder",
    message: "Your visit with Dr. Anwar Hussain Chen is tomorrow at 10:30 AM.",
    time: "2h ago",
    type: "appointment",
    read: false,
  },
  {
    id: "notif-2",
    title: "Lab report ready",
    message: "Your Complete Blood Count results are now available.",
    time: "1d ago",
    type: "lab",
    read: false,
  },
  {
    id: "notif-3",
    title: "Refill due soon",
    message: "Your Atorvastatin refill is due in 3 days.",
    time: "2d ago",
    type: "prescription",
    read: true,
  },
  {
    id: "notif-4",
    title: "Payment pending",
    message: "A pharmacy bill of Rs4500.00 is awaiting payment.",
    time: "3d ago",
    type: "payment",
    read: true,
  },
  {
    id: "notif-5",
    title: "Profile updated",
    message: "Your contact information was changed successfully.",
    time: "5d ago",
    type: "general",
    read: true,
  },
];

export const healthTips: HealthTip[] = [
  {
    id: "tip-1",
    title: "Stay ahead of hydration",
    description:
      "Aim for 8 glasses of water a day — it supports kidney function and keeps energy levels steady.",
    category: "Wellness",
  },
  {
    id: "tip-2",
    title: "Ease up on saturated fat",
    description:
      "More fibre, less saturated fat — small swaps that help keep your cholesterol trend heading the right way.",
    category: "Heart Health",
  },
  {
    id: "tip-3",
    title: "Protect your sleep window",
    description:
      "7–9 hours of consistent sleep helps regulate blood sugar and supports your immune system.",
    category: "Sleep",
  },
];

export const vitals: Vital[] = [
  {
    id: "v-1",
    label: "Blood Pressure",
    value: "118/76",
    unit: "mmHg",
    status: "normal",
    trend: "flat",
    reading: "Aug 10, 2026",
  },
  {
    id: "v-2",
    label: "Heart Rate",
    value: "72",
    unit: "bpm",
    status: "normal",
    trend: "down",
    reading: "Aug 10, 2026",
  },
  {
    id: "v-3",
    label: "Blood Glucose",
    value: "98",
    unit: "mg/dL",
    status: "normal",
    trend: "flat",
    reading: "Aug 5, 2026",
  },
  {
    id: "v-4",
    label: "Weight",
    value: "65",
    unit: "kg",
    status: "normal",
    trend: "down",
    reading: "Aug 10, 2026",
  },
  {
    id: "v-5",
    label: "BMI",
    value: "22.4",
    unit: "kg/m²",
    status: "normal",
    trend: "flat",
    reading: "Aug 10, 2026",
  },
];
